name: "Publish to Docker Hub"

on:
  push:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:

jobs:
  publish_7x:
    name: "7.x"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        elasticsearch-version:
          - "7.7"
          - "7.6"
          - "7.9"
          - "7.16"
          - "7.17"

    steps:
      - name: "Prepare the build context"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Publish the Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.elasticsearch-version }}/
          tags: ajardin/magento2-elasticsearch:${{ matrix.elasticsearch-version }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ajardin/magento2-elasticsearch:${{ matrix.elasticsearch-version }}
          cache-to: type=inline
